/*
FILE PATH: exchange/keystore/keystore_secp256k1.go

DESCRIPTION:

	secp256k1 implementation surface for MemoryKeyStore. The Attesta
	protocol curve is secp256k1; every on-log entry's signature is
	over secp256k1 with SDK envelope SigAlgoECDSA. JN historically
	only had Ed25519 here, which is why the legacy Sign path returned
	a curve that the entry envelope's verifier rejected.

	These methods are the fix for that mismatch:

	  - GenerateSecp256k1: provision a new secp256k1 keypair
	    for a DID. KeyInfo.Curve = CurveSecp256k1; PublicKey is the
	    65-byte uncompressed (0x04 prefix) form expected by the SDK.
	  - SignSecp256k1: sign a 32-byte typed-data digest. Returns the
	    65-byte SignCompact output (recoveryByte || R || S) — the
	    wire format Privy returns and the SDK accepts. Callers MUST
	    compute the EIP-712-style typed-data digest themselves; the
	    keystore signs the bytes given.
	  - PublicKeySecp256k1: return the bound 65-byte uncompressed
	    public key.

	Production deployments route user-DID signing through the
	IdentityProvider (Privy) rather than this keystore. This keystore
	holds system DIDs (institutional/ledger keys) used at
	bootstrap and for protocol-level entries the ledger publishes.

KEY DEPENDENCIES:
  - github.com/decred/dcrd/dcrec/secp256k1/v4 (curve operations).
  - github.com/decred/dcrd/dcrec/secp256k1/v4/ecdsa (SignCompact).
*/
package keystore

import (
	"fmt"
	"time"

	"github.com/decred/dcrd/dcrec/secp256k1/v4"
	"github.com/decred/dcrd/dcrec/secp256k1/v4/ecdsa"
)

// GenerateSecp256k1 creates and stores a new secp256k1 keypair for
// the DID. Returns KeyInfo with Curve=CurveSecp256k1 and PublicKey
// set to the 65-byte uncompressed (0x04 prefix) public key.
//
// If a secp256k1 key for did already exists, it is replaced (the
// caller's responsibility — typically rotation or test reset).
func (m *MemoryKeyStore) GenerateSecp256k1(did string, purpose string) (*KeyInfo, error) {
	if did == "" {
		return nil, fmt.Errorf("keystore: GenerateSecp256k1: did required")
	}
	priv, err := secp256k1.GeneratePrivateKey()
	if err != nil {
		return nil, fmt.Errorf("keystore: GenerateSecp256k1: %w", err)
	}

	info := &KeyInfo{
		KeyID:     fmt.Sprintf("%s#secp256k1-1", did),
		DID:       did,
		Purpose:   purpose,
		Curve:     CurveSecp256k1,
		PublicKey: priv.PubKey().SerializeUncompressed(),
		Created:   time.Now().UTC(),
	}

	m.mu.Lock()
	m.keysSecp[did] = &managedSecpKey{info: info, privateKey: priv}
	m.mu.Unlock()

	return info, nil
}

// ImportSecp256k1 binds a caller-supplied private key to the DID.
// Used by escrow recovery, deterministic test fixtures, and the
// ledger bootstrap path. The caller MUST ensure the key was
// generated by a secure path — the keystore performs no provenance
// check.
func (m *MemoryKeyStore) ImportSecp256k1(did string, purpose string, priv *secp256k1.PrivateKey) (*KeyInfo, error) {
	if did == "" {
		return nil, fmt.Errorf("keystore: ImportSecp256k1: did required")
	}
	if priv == nil {
		return nil, fmt.Errorf("keystore: ImportSecp256k1: nil key")
	}
	info := &KeyInfo{
		KeyID:     fmt.Sprintf("%s#secp256k1-1", did),
		DID:       did,
		Purpose:   purpose,
		Curve:     CurveSecp256k1,
		PublicKey: priv.PubKey().SerializeUncompressed(),
		Created:   time.Now().UTC(),
	}
	m.mu.Lock()
	m.keysSecp[did] = &managedSecpKey{info: info, privateKey: priv}
	m.mu.Unlock()
	return info, nil
}

// SignSecp256k1 signs the 32-byte digest with the secp256k1 key
// for did. Returns the 65-byte SignCompact output — the wire format
// the Attesta SDK and Privy both produce/consume.
//
// The keystore does NOT hash again. Callers compute the typed-data
// digest (EIP-712-style) and pass it verbatim. This is the same
// contract as IdentityProvider.SignDigest; the two backends are
// swappable at the call site.
func (m *MemoryKeyStore) SignSecp256k1(did string, digest [32]byte) ([]byte, error) {
	m.mu.RLock()
	mk, ok := m.keysSecp[did]
	m.mu.RUnlock()

	if !ok {
		return nil, fmt.Errorf("keystore: no secp256k1 key for %s", did)
	}
	return ecdsa.SignCompact(mk.privateKey, digest[:], false), nil
}

// PublicKeySecp256k1 returns the 65-byte uncompressed (0x04 prefix)
// public key for did. Returns an error if the DID has no secp256k1
// key. The returned slice is a fresh copy; callers may mutate freely.
func (m *MemoryKeyStore) PublicKeySecp256k1(did string) ([]byte, error) {
	m.mu.RLock()
	mk, ok := m.keysSecp[did]
	m.mu.RUnlock()

	if !ok {
		return nil, fmt.Errorf("keystore: no secp256k1 key for %s", did)
	}
	out := make([]byte, len(mk.info.PublicKey))
	copy(out, mk.info.PublicKey)
	return out, nil
}
